### PR TITLE
Refresh media attachment's identifier after paste

### LINKED ISSUE #923: The pasted attachment's identifier and copied attachment's identifier are same
### Expected behavior

Copy one or more attachment(s) and paste, the pasted attachments' identifiers are same as the copied attachment(s)

### Actual behavior

The pasted attachment's identifier should be different from copied attachment

### Steps to reproduce the behavior

1. Insert image to the editor
2. Copy the inserted image
3. Paste in editor
4. compare their identifiers

### PR DESCRIPTION
**Pull request by azone**
The pasted identifier should be different from copied attachment

Fixes #923

To test:

1. Insert image to the editor
2. Copy the inserted image
3. Paste in editor
4. compare their identifiers

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@SergioEstevao - Since you're our media expert, can you give this PR a look?

**Comment by SergioEstevao** [comment]
This is looking good, but there is a test failing on the original commit, @azone can you please update this with the latest code from the develop branch?

**Comment by diegoreymendez** [comment]
@SergioEstevao - Was wondering if this should be merged or closed.  Can you comment?  Thanks!

**Comment by SergioEstevao** [comment]
This can be merged now that tests are working ok.

**Pull request merged**
