### PR TITLE
Adds partial support for RTL languages.

### PR DESCRIPTION
**Pull request by diegoreymendez**
## Description:

Addresses a first part of #861 .

Outputs the writing direction to HTML.

## Testing:

1. Add the Arabic keyboard to your device.
2. Launch the editor.
3. Type a line in Arabic - make sure it's recognized as right-to-left text in visual mode.
4. Switch to HTML mode.

Make sure the paragraph or block level element has a `dir="rtl"` attribute.

Important: the conversion back to visual mode is not supported yet.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Nice findings @jklausa.

Even though the reported issue goes a bit beyond scope of this PR, I added [a note in the main issue](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/861#issuecomment-353117717) that it needs to be resolved for the feature to be considered "complete".

**Comment by diegoreymendez** [comment]
@jklausa, @jleandroperez - Can I ask for a review?

**Comment by diegoreymendez** [comment]
Digging deeper cos the unit tests seem to be failing.

I think I've surfaced an issue with `HeaderFormatter` in this PR.

**Comment by jklausa** [comment]
Hrm, but the unit tests passed in d718ac8 — only the UI ones failed (which I presumed to just be the usual Xcode UI testing flakiness). Interesting.

**Comment by diegoreymendez** [comment]
Tests fixed, merging.

**Pull request merged**
