### PR TITLE
Remove outdated documentation.

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR removes some outdated documentation from the repo.

To test:
 - Just check that files are removed from the project in Xcode and from the file system.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
I'm not sure if we should remove these or update the documentation.  Thoughts, @SergioEstevao and @jleandroperez?

**Comment by SergioEstevao** [comment]
I think we should remove this, and then create new updated documentation. 

And I think the docs should be done on the Markdown format in order to be readable directly on Github.

**Comment by jleandroperez** [comment]
Maybe we only remove *EditingLogic*, since it's the one no longer valid?

**Comment by diegoreymendez** [comment]
@jleandroperez - Is `UnsupportedTags.rtf` up to date?

**Comment by SergioEstevao** [comment]
If we keep UnsupportedTags I can convert that to a MD document, probably even add then to the README section for now.

When the documentation grows bigger we can split in multiple files.

**Comment by jleandroperez** [comment]
@diegoreymendez `UnsupportedTags.rtf` is still valid, but a bit incomplete, since there are a ton of other unsupported tags, such as:

- TABLE
- SELECT / OPTION
- (And so on!!)

**Pull request merged**
