### PR TITLE
Issue/605 build step check for carthage update

### PR DESCRIPTION
**Pull request by arisun**
Fixes #
build step to run carthage update command
To test:
download the source code from repo
run/build/test/profile/archive the project
check whether a terminal window opens up, and execute the 'carthage update' based on the existence of the folder 'iOS' inside Carthage > Build

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@arisun I think you branched from a PR that isn't the current develop on the main branch.

You need to redo your PR using the current develop has source.

**Comment by arisun** [comment]
@SergioEstevao 
I have created the branch from develop, prior to that i have created a PR to get the update from main branch.

**Comment by SergioEstevao** [comment]
@arisun it's strange because your PR it's catching a lot of changes comparing to our develop.

**Comment by arisun** [comment]
@SergioEstevao 
shall i create a new branch and push the changes ?

**Comment by SergioEstevao** [comment]
@arisun yes please.

**Comment by arisun** [comment]
closing the PR

**Pull request closed without merging**
