### PR TITLE
Add tests for testing multiple figures in sequence.

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR at the moment is just a starting point to try and track the issue with image with captions on a sequence not being parsed correctly.

The issue looks to be in the serialization of the `figure` element back to HTML not in the caption shortcode processor.

To test:
 - Run the unit tests
 - See the `testMultipleFigureCaptionAreProperlyParsed()` test fail

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@SergioEstevao - I'm torn about merging this to develop cos my fix will take a while to make it through... can you target this to `issue/934-paragraph-style-merging-logic-needs-update` instead?

**Comment by SergioEstevao** [comment]
@diegoreymendez changed the base as you proposed.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Can we close this one if we merge the tests into https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1002?

**Comment by diegoreymendez** [comment]
Cherry-picked these tests into https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1002 and fixed the one that was breaking.

**Pull request closed without merging**
