### PR TITLE
TextView: Fixed undo issue of blockquote, pre, ordered list and unordered list

### LINKED ISSUE #844: Undo Issue of blockquote, pre, ordered list and unordered list
### Expected behavior

All those elements can undo perfectly when double press return(remove those attributes)

### Actual behavior

Undo manager reseted after double press return

### Steps to reproduce the behavior

1. input any characters 
2. apply them to blockquote, pre, ordered list or unordered list
3. press return
4. press return
5. do undo operation(shake the device)

### PR DESCRIPTION
**Pull request by azone**
Fixes #844

To test:

1. input any characters
2. apply them to blockquote, pre, ordered list or unordered list
3. press return
4. press return
5. do undo operation(shake the device)

### CODE REVIEW

**Comment by diegoreymendez** [comment]
For context: @jleandroperez is evaluating alternatives to make the undo manager work fine.

**Comment by SergioEstevao** [comment]
@azone I've tested this on the latest version and it looks it's working better, was the bug related to missing a step on the undo, where we have a empty line with the style applied?

**Comment by azone** [comment]
@SergioEstevao Perhaps the last version resolved this issue.

**Comment by diegoreymendez** [comment]
Closing, since undo seems to be working fine now.

**Pull request closed without merging**
