### PR TITLE
issue 605, carthage update build script

### LINKED ISSUE #605: Add a build step to check if the user has run `carthage update` in the Example folder.
When checking out the project from scratch, trying to build the Example app doesn't work unless the user has run `carthage update` in the Example folder.

We should add a script as a build step to check if the command was run by the user.

### PR DESCRIPTION
**Pull request by arisun**
Fixes #605 

To test:

### CODE REVIEW

**Comment by arisun** [comment]
@SergioEstevao 
pushed the changes. Please review & confirm.

**Comment by arisun** [comment]
@SergioEstevao 
Required your help to merge the changes into 'develop' branch, but travis CI showing error.
Could you please help to identify the issue, so i can proceed accordingly.

**Comment by diegoreymendez** [comment]
@arisun - Adding myself as reviewer as well.  Can you move the script to the `/Scripts` directory?

I'll see if I find why Travis is failing as well.

**Comment by arisun** [comment]
@diegoreymendez as suggested moved the file 'Scripts' folder.

**Pull request merged**
