### PR TITLE
Try/refactor media attachment

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR changes the way attributes for MediaAttachment are implemented, instead of having custom properties directly implemented in the ImageAttachment and VideoAttachment, all the properties are stored and accessed through the use of `extraAttributes` property, and are calculated variables implemented in extensions.

In my point of view this has the following advantages:

- Simpler parser and serialiser, because we don't need to do extra steps for the specific properties
- Allows expansibility of properties by the users of the library.
- Still allows to create specific enums for properties to make it easier to use.

To test:
 - Check if the project compile and unit test are ok.
 - Start the app, check interactions with image and video are working ok.

### CODE REVIEW

**Comment by jklausa** [comment]
I really like the simplification and moving the responsibility here! 

My only nitpick would be that the `size` and `alignment` setters/getters are almost identical — maybe it would be possible to extract them into their own thing?

**Comment by SergioEstevao** [comment]
@jklausa good point I think I can introduce an helper method to allow changes on the html class attribute.

**Comment by diegoreymendez** [comment]
In this proposal, it seems like we're simplifying the converters, but what we're really doing is moving that complexity to the [setters and getters](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/847/files#diff-d8a133f794ed76fc0e76e3f633a1cf51R160).

That's much more complexity that I'd like to see executed each time a setter and / or getter gets called.

Doing [part of the HTML conversion](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/847/files#diff-d8a133f794ed76fc0e76e3f633a1cf51R111) inside of getters and setters in attachments is breaking the design responsibility of converters taking care of that in a single step.

We do need to simplify our formatters but I don't see this being the right direction.

We should instead make the conversion step customizable.

**Comment by SergioEstevao** [comment]
@diegoreymendez keep in mind that the `class` attribute is one of the more complex attributes in html and as @jklausa says I can simplify the code to have a single method to set class attributes.

One thing that I don't like on the current approach is that attributes like size, that in the current format are specific to WordPress are part of the Aztec implementation. This implementation will allow to move it out completely of Aztec pod.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Mind if we close this for now?

**Comment by diegoreymendez** [comment]
Closing.

**Pull request closed without merging**
